gg:
  jte:
    usePrecompiledTemplates: true
# for development, comment the previous line, and uncomment the following; insta-reload of JTEs
#    development-mode: true
spring:
  application:
    name: billetterie
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://host/mydb?user=username&password=password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_SERVER:in-v3.mailjet.com}
    username: ${MAIL_USER:}
    password: ${MAIL_PASSWORD:}
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true
      #mail.smtp.debug: true # uncomment to have SMTP exchanges logged to the console
    # switch to on when credentials are confirmed
    # if `on`, the app will fail to launch if the connection to the SMTP server fails
    test-connection: off
  messages:
    fallback-to-system-locale: false
  profiles:
    group:
      local-mail: local,mailhog

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: threaddump, heapdump
    access:
      default: read_only
  endpoint:
    health:
      show-details: always
      probes:
        add-additional-paths: on
        enabled: on

app:
  admin:
    actuator-password: ${ACTUATOR_PASSWORD:actuator} # the user is hardcoded as `actuator`
    admin-username: ${ADMIN_USER:admin}
    admin-password: ${ADMIN_PASSWORD:password}
    session-cookie-name: ${ADMIN_SESSION_COOKIE_NAME:BILLETTERIE_SESSION} # we name the cookie, for fun and to clean it
  mail:
    from:
      address: devoxx4kidsqc@montreal-jug.org
      name: Devoxx4Kids Québec
    reply-to:
      address: devoxx4kidsqc@montreal-jug.org
      name: Devoxx4Kids Québec
  # prod key will be different ;-)
  rsaKey: |
    -----BEGIN PRIVATE KEY-----
    hello
    -----END PRIVATE KEY-----
