name: Deploy static assets on GitHub page

on:
  push:
    branches: ["main"]
    paths: ["static-assets/**", "!static-assets/README.md"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build static asset content
        run: rm -f ./static-assets/README.md
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: static-assets/
      - name: Deploy to GitHub Pages
        id: deploy-static-assets
        uses: actions/deploy-pages@v4
